apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollapp
  namespace: argocd

spec:
  destination:
    namespace: rollapp
    server: https://kubernetes.default.svc
  project: default

  source:
    repoURL: 
    targetRevision: 
    path: 

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
